# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5770aee561025147a279e4da61051a8bc53d0f75e30c56e6a2656210802f1f26c1f1053b864564155e06d83f58d8a32ddfc53399893040a215f3d75aef6504f

test:
  secret_key_base: f9d6780288bdd1d1b965abb1b31a3009bfc3fe4c0dda9b0032112b9f6b60745fd21efa01cc7959095c46b11efa0eead2bebaf49d4e4e8d823da7f40a6b8c84a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
